[LIBS-312] Only install if not found

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -103,7 +103,11 @@ miseInstall() {
 main() {
 	setToolVersions "$BUILDKITE_PLUGIN_MISE_TOOL_VERSIONS"
 
-	setupMise "$BUILDKITE_PLUGIN_MISE_VERSION"
+
+    if ! command -v mise &>/dev/null; then
+      echo "mise not found. Installing."
+      setupMise "$BUILDKITE_PLUGIN_MISE_VERSION"
+    fi
 
 	# export MISE_TRUSTED_CONFIG_PATHS="$(pwd)"
 	# export MISE_YES=1
